version: 2

seeds:
  - name: nfl_elo
    tests:
      - unique:
          column_name: "(date || '-' || team1 || '-' || team2)"
      - not_null:
          column_name: "(date || '-' || team1 || '-' || team2)"