config:
  use_colors: false
dbt_analytics: #PROJECT ONE
  target: dev
  outputs:
    dev:
      account: mob60112.us-east-1
      client_session_keep_alive: false
      database: dbt
      password: '{{ env_var(''SNOWFLAKE_PASS'') }}'
      query_tag: dbt
      role: dbt_developer
      schema: public
      threads: 4
      type: snowflake
      user: '{{ env_var(''SNOWFLAKE_USER'') }}'
      warehouse: dbt_wh
    prod:
      account: mob60112.us-east-1
      client_session_keep_alive: false
      database: dbt
      password: '{{ env_var(''PASS'') }}'
      query_tag: dbt
      role: dbt_developer
      schema: public
      threads: 4
      type: snowflake
      user: '{{ env_var(''USER'') }}'
      warehouse: dbt_wh
