
SELECT
DATE,
SEASON,
CAST(NEUTRAL AS BOOLEAN) AS NEUTRAL,
CAST(PLAYOFF AS VARCHAR(256)) AS PLAYOFF,
CAST(TEAM1 AS VARCHAR(3)) AS TEAM1,
CAST(TEAM1 AS VARCHAR(3)) AS TEAM2,
CAST(ELO1_PRE AS DECIMAL(10,3)) AS ELO1_PRE,
CAST(ELO2_PRE AS DECIMAL(10,3)) AS ELO2_PRE,
CAST(ELO_PROB1 AS DOUBLE) AS ELO_PROB1,
CAST(ELO_PROB2 AS DOUBLE) AS ELO_PROB2,
CAST(ELO1_POST AS DECIMAL(10,4)) AS ELO1_POST,
CAST(ELO2_POST AS DECIMAL(10,4)) AS ELO2_POST,
SCORE1,
SCORE2
FROM {{ source('public', 'nfl_elo') }} -- This is a jinja reference to a models/sources.yml key-value pair.

