
SELECT
SEASON AS YR,
TEAM,
COUNT(DISTINCT(SEASON)) AS SEASONS,
COUNT(1) AS TOTAL_GAMES,
SUM(WIN) AS TOTAL_WINS,
SUM(CASE WHEN WIN = 0 and DRAW = 0 THEN 1 ELSE 0 END) AS TOTAL_LOSSES,
SUM(DRAW) AS TOTAL_DRAWS,
MIN(ELO_POST) AS MIN_ELO,
MAX(ELO_POST) AS MAX_ELO,
AVG(ELO_POST) AS AVG_ELO
FROM {{ (ref('team_elo_by_game')) }}
GROUP BY
SEASON,
TEAM
ORDER BY YR ASC, TEAM ASC