
{{
config(
materialized = 'ephemeral',
)
}}

SELECT
match_date,
TEAM1 AS TEAM,
SEASON AS SEASON,
ELO1_PRE AS ELO_PRE,
ELO_PROB1 AS ELO_PROB,
ELO1_POST AS ELO_POST,
SCORE1 AS SCORE,
CASE WHEN SCORE1 > SCORE2 THEN 1 ELSE 0 END AS WIN,
CASE WHEN SCORE1 = SCORE2 THEN 1 ELSE 0 END AS DRAW
FROM {{ ref('v_nfl_elo') }}
UNION
SELECT
match_date,
TEAM2 AS TEAM,
SEASON AS SEASON,
ELO2_PRE AS ELO_PRE,
ELO_PROB2 AS ELO_PROB,
ELO2_POST AS ELO_POST,
SCORE2 AS SCORE,
CASE WHEN SCORE1 < SCORE2 THEN 1 ELSE 0 END AS WIN,
CASE WHEN SCORE1 = SCORE2 THEN 1 ELSE 0 END AS DRAW
FROM {{ ref('v_nfl_elo') }}



